spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/im
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: chuxiwen

mybatis:
  #  mybatis mapper映射文件路径
  mapper-locations: classpath*:mapper/*.xml
  #  打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
